server.port=${PORT:8080}
server.address=0.0.0.0
spring.application.name=GEMA Web
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=35MB
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
spring.web.resources.cache.cachecontrol.max-age=3600
